Hot fix: feature/footer
NunNunIT/forcat-website-front-end pull request #11
Opened 2024-03-13 15:02 UTC by fredle09

Adding missing properties in <Image>

2024-03-13 15:40 UTC, namtuthien requested changes

2024-03-13 15:40 UTC, namtuthien commented on src/components/customer/logo/index.tsx
> +        width={140}
ko inline css

2024-03-13 22:12 UTC, fredle09 commented on src/components/customer/logo/index.tsx
> +        width={140}
Cái này đã được sửa bên trong feature/header

2024-03-14 00:57 UTC, namtuthien approved these changes

2024-03-14 00:57 UTC, merged